// lib/index.cjs — NiyoX AI SDK  (CommonJS — auto-generated by scripts/build.js)
"use strict";

// ─── client.js ───────────────────────────────────────────────────────────────
// src/client.js — NiyoX AI Core Client  v0.0.4
"use strict";

const BASE_URL = "https://ai.dnuz.top/api/ai";

/**
 * NiyoXClient — the core wrapper around the NiyoX AI REST API.
 *
 * v0.0.4 — Context & Memory additions:
 *   • Persona / system prompt  — set once, prepended to every message
 *   • Context window trimming  — auto-prune oldest turns when history is too long
 *   • Conversation export      — dump history as JSON or plain text
 */
class NiyoXClient {
  /**
   * @param {object}  options
   * @param {string}  [options.sessionId="default"]
   * @param {string}  [options.conversationId=null]
   * @param {number}  [options.timeout=30000]           ms per request
   * @param {string}  [options.persona=null]            System-prompt / persona string
   * @param {number}  [options.maxHistory=50]           Max history *entries* (pairs = maxHistory/2).
   *                                                    0 = unlimited.
   */
  constructor(options = {}) {
    this.sessionId       = options.sessionId       || "default";
    this.conversationId  = options.conversationId  || null;
    this.timeout         = options.timeout         || 30000;
    this.history         = [];

    // ── v0.0.4: Context & Memory ──────────────────────────────────────────
    this._persona        = options.persona    || null;   // system prompt string
    this._maxHistory     = options.maxHistory != null ? options.maxHistory : 50; // 0 = unlimited
  }

  // ── Persona / system-prompt ─────────────────────────────────────────────

  /**
   * Set (or clear) the AI persona / system prompt.
   * The persona is transparently prepended to every outgoing message.
   *
   * @param {string|null} text  Pass null or "" to clear.
   * @returns {NiyoXClient}     Chainable.
   *
   * @example
   *   client.setPersona("You are a concise coding assistant. Respond only in code.");
   */
  setPersona(text) {
    this._persona = text ? String(text).trim() : null;
    return this;
  }

  /** Get the currently active persona string (or null). */
  getPersona() { return this._persona; }

  /**
   * Compose the actual query to send, injecting the persona when set.
   * Format:  "[SYSTEM: <persona>]\n\nUser: <message>"
   * @private
   */
  _buildQuery(message) {
    if (!this._persona) return message;
    return `[SYSTEM: ${this._persona}]\n\nUser: ${message}`;
  }

  // ── Context window trimming ─────────────────────────────────────────────

  /**
   * Set the maximum number of history *entries* kept in memory.
   * One chat turn = 2 entries (user + assistant).
   * When the limit is exceeded the oldest entries are pruned.
   *
   * @param {number} max  Set to 0 for unlimited.
   * @returns {NiyoXClient} Chainable.
   *
   * @example
   *   client.setMaxHistory(20);  // keep last 10 turns
   */
  setMaxHistory(max) {
    this._maxHistory = Number(max) || 0;
    this._trimHistory();
    return this;
  }

  /** Get the current maxHistory limit. */
  getMaxHistory() { return this._maxHistory; }

  /** @private — prune oldest entries when over the limit */
  _trimHistory() {
    if (this._maxHistory > 0 && this.history.length > this._maxHistory) {
      this.history = this.history.slice(this.history.length - this._maxHistory);
    }
  }

  // ── Core chat ───────────────────────────────────────────────────────────

  /**
   * Send a message to NiyoX AI and get a response.
   * @param {string} message
   * @returns {Promise<{result: string, conversationId: string, responseTime: number}>}
   */
  async chat(message) {
    const query  = this._buildQuery(message);
    const params = new URLSearchParams({ q: query });
    if (this.conversationId) params.append("conversationId", this.conversationId);
    if (this.sessionId !== "default") params.append("sessionId", this.sessionId);

    const url = `${BASE_URL}?${params.toString()}`;

    const fetch = globalThis.fetch ?? (await import("node-fetch").then(m => m.default).catch(() => null));
    if (!fetch) throw new Error("No fetch available — install node-fetch or use Node 18+");

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeout);

    let data;
    try {
      const res = await fetch(url, { signal: controller.signal });
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      data = await res.json();
    } finally {
      clearTimeout(timer);
    }

    if (!data.success) throw new Error("API returned success=false");

    if (data.conversationId) this.conversationId = data.conversationId;

    this.history.push({ role: "user",      content: message,     timestamp: new Date() });
    this.history.push({ role: "assistant", content: data.result, timestamp: new Date(), responseTime: data.responseTime });

    // Auto-trim after each turn
    this._trimHistory();

    return {
      result:         data.result,
      conversationId: data.conversationId,
      sessionId:      data.sessionId,
      responseTime:   data.responseTime,
      attempts:       data.attempts,
    };
  }

  /** Alias for chat() */
  async ask(message) { return this.chat(message); }

  /** Clear in-memory history and start a fresh conversation */
  newConversation() {
    this.conversationId = null;
    this.history = [];
  }

  /** Get in-memory chat history (returns a copy) */
  getHistory() { return [...this.history]; }

  // ── Conversation export ─────────────────────────────────────────────────

  /**
   * Export the current in-memory conversation.
   *
   * @param {"json"|"text"|"markdown"} [format="json"]
   * @returns {string}
   *
   * @example
   *   const json = client.exportConversation("json");
   *   fs.writeFileSync("chat.json", json);
   *
   *   const txt = client.exportConversation("text");
   *   console.log(txt);
   */
  exportConversation(format = "json") {
    const fmt = String(format).toLowerCase();

    if (fmt === "json") {
      return JSON.stringify({
        exportedAt:     new Date().toISOString(),
        conversationId: this.conversationId,
        sessionId:      this.sessionId,
        persona:        this._persona,
        messages:       this.history,
      }, null, 2);
    }

    if (fmt === "text") {
      const lines = [];
      if (this._persona)        lines.push(`[Persona: ${this._persona}]\n`);
      if (this.conversationId)  lines.push(`Conversation ID: ${this.conversationId}\n`);
      for (const entry of this.history) {
        const ts    = entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString() : "";
        const label = entry.role === "user" ? "You" : "NiyoX AI";
        const meta  = entry.responseTime ? ` (${entry.responseTime}ms)` : "";
        lines.push(`[${ts}] ${label}${meta}:\n${entry.content}\n`);
      }
      return lines.join("\n");
    }

    if (fmt === "markdown") {
      const lines = [`# NiyoX AI Conversation\n`];
      if (this._persona)        lines.push(`> **Persona:** ${this._persona}\n`);
      if (this.conversationId)  lines.push(`> **ID:** \`${this.conversationId}\`\n`);
      lines.push(`> **Exported:** ${new Date().toISOString()}\n\n---\n`);
      for (const entry of this.history) {
        const ts    = entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString() : "";
        const label = entry.role === "user" ? "**You**" : "**NiyoX AI**";
        const meta  = entry.responseTime ? ` *(${entry.responseTime}ms)*` : "";
        lines.push(`### ${label} — ${ts}${meta}\n\n${entry.content}\n`);
      }
      return lines.join("\n");
    }

    throw new Error(`Unknown export format "${format}". Use "json", "text", or "markdown".`);
  }
}

// ─── storage.js ──────────────────────────────────────────────────────────────
// src/storage.js — Optional MongoDB persistence layer  v0.0.4
"use strict";

const DEFAULT_MONGO_URI = "mongodb+srv://danuzdev_db_user:eUcIyqvRaNEKnAtA@niyoxai.tzrs4rg.mongodb.net/";
const DEFAULT_DB_NAME   = "niyox_npm";

const _cache = new Map();

async function getDb(uri = DEFAULT_MONGO_URI, dbName = DEFAULT_DB_NAME) {
  const cacheKey = `${uri}::${dbName}`;
  if (_cache.has(cacheKey)) return _cache.get(cacheKey).db;
  try {
    const { MongoClient } = require("mongodb");
    const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });
    await client.connect();
    const db = client.db(dbName);
    _cache.set(cacheKey, { client, db });
    return db;
  } catch (err) {
    throw new Error(`MongoDB connection failed: ${err.message}`);
  }
}

async function closeDb(uri = DEFAULT_MONGO_URI, dbName = DEFAULT_DB_NAME) {
  const cacheKey = `${uri}::${dbName}`;
  const entry = _cache.get(cacheKey);
  if (entry) {
    await entry.client.close();
    _cache.delete(cacheKey);
  }
}

async function closeAllDb() {
  for (const [, entry] of _cache) await entry.client.close();
  _cache.clear();
}

/**
 * NiyoXStorage — handles optional persistent chat/session storage.
 *
 * v0.0.4 — Context & Memory additions:
 *   • savePersona / getPersona   — persist AI persona per-user in MongoDB
 *   • exportConversation         — export a stored conversation as JSON / text / markdown
 */
class NiyoXStorage {
  constructor(userId = "anonymous", options = {}) {
    this.userId   = userId;
    this.mongoUri = options.mongoUri || DEFAULT_MONGO_URI;
    this.dbName   = options.dbName   || DEFAULT_DB_NAME;
    this.enabled  = false;
  }

  _getDb() { return getDb(this.mongoUri, this.dbName); }

  async connect(userId, mongoUri, dbName) {
    if (userId)   this.userId   = userId;
    if (mongoUri) this.mongoUri = mongoUri;
    if (dbName)   this.dbName   = dbName;
    await this._getDb();
    this.enabled = true;
    return this;
  }

  // ── Messages ─────────────────────────────────────────────────────────────

  async saveMessage({ conversationId, role, content, responseTime = null }) {
    if (!this.enabled) return null;
    const db   = await this._getDb();
    const doc  = { userId: this.userId, conversationId, role, content, responseTime, createdAt: new Date() };
    const res  = await db.collection("messages").insertOne(doc);
    return res.insertedId;
  }

  async saveTurn({ conversationId, userMessage, assistantMessage, responseTime }) {
    if (!this.enabled) return;
    await Promise.all([
      this.saveMessage({ conversationId, role: "user",      content: userMessage }),
      this.saveMessage({ conversationId, role: "assistant", content: assistantMessage, responseTime }),
    ]);
  }

  async getConversation(conversationId) {
    if (!this.enabled) return [];
    const db = await this._getDb();
    return db.collection("messages")
      .find({ conversationId, userId: this.userId })
      .sort({ createdAt: 1 })
      .toArray();
  }

  async listConversations() {
    if (!this.enabled) return [];
    const db = await this._getDb();
    return db.collection("messages").distinct("conversationId", { userId: this.userId });
  }

  async deleteConversation(conversationId) {
    if (!this.enabled) return 0;
    const db  = await this._getDb();
    const res = await db.collection("messages").deleteMany({ conversationId, userId: this.userId });
    return res.deletedCount;
  }

  // ── Persona persistence (v0.0.4) ─────────────────────────────────────────

  /**
   * Persist the user's preferred AI persona to MongoDB.
   * Automatically applied by NiyoXAI.enableStorage() if the client has no persona set.
   *
   * @param {string|null} persona  Pass null to clear.
   *
   * @example
   *   await store.savePersona("You are a friendly cooking assistant.");
   */
  async savePersona(persona) {
    return this.setPref("__persona__", persona ?? null);
  }

  /**
   * Load the persisted persona for this user.
   * @returns {Promise<string|null>}
   */
  async getPersona() {
    return this.getPref("__persona__", null);
  }

  // ── Conversation export (v0.0.4) ─────────────────────────────────────────

  /**
   * Export a stored conversation from MongoDB as a formatted string.
   *
   * @param {string}                    conversationId
   * @param {"json"|"text"|"markdown"}  [format="json"]
   * @returns {Promise<string>}
   *
   * @example
   *   const md = await store.exportConversation("conv-abc-123", "markdown");
   *   fs.writeFileSync("chat.md", md);
   */
  async exportConversation(conversationId, format = "json") {
    const messages = await this.getConversation(conversationId);
    const fmt      = String(format).toLowerCase();

    if (fmt === "json") {
      return JSON.stringify({
        exportedAt:     new Date().toISOString(),
        conversationId,
        userId:         this.userId,
        messages,
      }, null, 2);
    }

    if (fmt === "text") {
      const lines = [`Conversation: ${conversationId}\nUser: ${this.userId}\n`];
      for (const m of messages) {
        const ts    = m.createdAt ? new Date(m.createdAt).toLocaleString() : "";
        const label = m.role === "user" ? "You" : "NiyoX AI";
        const meta  = m.responseTime ? ` (${m.responseTime}ms)` : "";
        lines.push(`[${ts}] ${label}${meta}:\n${m.content}\n`);
      }
      return lines.join("\n");
    }

    if (fmt === "markdown") {
      const lines = [
        `# NiyoX AI Conversation\n`,
        `> **ID:** \`${conversationId}\`  `,
        `> **User:** ${this.userId}  `,
        `> **Exported:** ${new Date().toISOString()}\n\n---\n`,
      ];
      for (const m of messages) {
        const ts    = m.createdAt ? new Date(m.createdAt).toLocaleString() : "";
        const label = m.role === "user" ? "**You**" : "**NiyoX AI**";
        const meta  = m.responseTime ? ` *(${m.responseTime}ms)*` : "";
        lines.push(`### ${label} — ${ts}${meta}\n\n${m.content}\n`);
      }
      return lines.join("\n");
    }

    throw new Error(`Unknown export format "${format}". Use "json", "text", or "markdown".`);
  }

  // ── Preferences ───────────────────────────────────────────────────────────

  async setPref(key, value) {
    if (!this.enabled) return;
    const db = await this._getDb();
    await db.collection("user_prefs").updateOne(
      { userId: this.userId, key },
      { $set: { value, updatedAt: new Date() } },
      { upsert: true }
    );
  }

  async getPref(key, defaultValue = null) {
    if (!this.enabled) return defaultValue;
    const db  = await this._getDb();
    const doc = await db.collection("user_prefs").findOne({ userId: this.userId, key });
    return doc ? doc.value : defaultValue;
  }

  // ── Stats ─────────────────────────────────────────────────────────────────

  async getStats() {
    if (!this.enabled) return null;
    const db   = await this._getDb();
    const coll = db.collection("messages");
    const [total, conversations, avgTime] = await Promise.all([
      coll.countDocuments({ userId: this.userId }),
      coll.distinct("conversationId", { userId: this.userId }),
      coll.aggregate([
        { $match: { userId: this.userId, role: "assistant", responseTime: { $ne: null } } },
        { $group: { _id: null, avg: { $avg: "$responseTime" } } },
      ]).toArray(),
    ]);
    return {
      totalMessages:      total,
      totalConversations: conversations.length,
      avgResponseTimeMs:  avgTime[0]?.avg?.toFixed(0) ?? "N/A",
    };
  }

  async disconnect() {
    await closeDb(this.mongoUri, this.dbName);
    this.enabled = false;
  }
}

// ─── NiyoXAI high-level class ────────────────────────────────────────────────
/**
 * NiyoXAI — high-level SDK combining the API client + optional DB storage.
 *
 * Quick start:
 *   const { NiyoXAI } = require("niyox");
 *   const ai = new NiyoXAI();
 *   const { result } = await ai.chat("Hello!");
 *
 * With persona:
 *   const ai = new NiyoXAI({ persona: "You are a concise coding assistant." });
 *   // or later:
 *   ai.setPersona("You are a friendly chef.");
 *
 * With context trimming:
 *   const ai = new NiyoXAI({ maxHistory: 20 }); // keep last 10 turns
 *
 * With MongoDB + export:
 *   const ai = new NiyoXAI({ userId: "alice" });
 *   await ai.enableStorage();
 *   await ai.chat("Hello!");
 *   const md = await ai.exportConversation(ai.getConversationId(), "markdown");
 */
class NiyoXAI {
  constructor(options = {}) {
    this.client  = new NiyoXClient(options);
    this.storage = new NiyoXStorage(options.userId || "anonymous");
  }

  // ── Storage ───────────────────────────────────────────────────────────────

  /** Enable persistent MongoDB storage. Auto-loads saved persona if client has none set. */
  async enableStorage(userId) {
    await this.storage.connect(userId);
    // Auto-restore persisted persona if none is active
    if (!this.client.getPersona()) {
      const saved = await this.storage.getPersona();
      if (saved) this.client.setPersona(saved);
    }
    return this;
  }

  // ── Persona / system-prompt (v0.0.4) ─────────────────────────────────────

  /**
   * Set the AI persona / system prompt.
   * If storage is enabled the persona is also saved to MongoDB for future sessions.
   *
   * @param {string|null} text  Pass null or "" to clear.
   * @returns {Promise<NiyoXAI>} Chainable (awaitable).
   *
   * @example
   *   await ai.setPersona("You are a concise coding assistant.");
   */
  async setPersona(text) {
    this.client.setPersona(text);
    if (this.storage.enabled) await this.storage.savePersona(text || null);
    return this;
  }

  /** Get the currently active persona string (or null). */
  getPersona() { return this.client.getPersona(); }

  // ── Context window trimming (v0.0.4) ─────────────────────────────────────

  /**
   * Set the maximum number of in-memory history entries (1 turn = 2 entries).
   * Oldest entries are pruned automatically after each turn.
   * Set to 0 for unlimited.
   *
   * @param {number} max
   * @returns {NiyoXAI} Chainable.
   *
   * @example
   *   ai.setMaxHistory(20); // keep last 10 turns
   */
  setMaxHistory(max) {
    this.client.setMaxHistory(max);
    return this;
  }

  /** Get the current maxHistory limit. */
  getMaxHistory() { return this.client.getMaxHistory(); }

  // ── Chat ──────────────────────────────────────────────────────────────────

  /** Send a message; auto-persists if storage is enabled */
  async chat(message) {
    const response = await this.client.chat(message);
    if (this.storage.enabled) {
      await this.storage.saveTurn({
        conversationId:   response.conversationId,
        userMessage:      message,
        assistantMessage: response.result,
        responseTime:     response.responseTime,
      });
    }
    return response;
  }

  /** Alias */
  async ask(message) { return this.chat(message); }

  /** Start a fresh conversation thread */
  newConversation() { this.client.newConversation(); }

  /** Get the active conversationId (null until first message sent) */
  getConversationId() { return this.client.conversationId; }

  /** In-memory history for the current session */
  getHistory() { return this.client.getHistory(); }

  // ── Conversation export (v0.0.4) ──────────────────────────────────────────

  /**
   * Export a conversation as a formatted string.
   *
   * Without storage  → exports the current in-memory session.
   * With storage     → exports the stored MongoDB conversation for `conversationId`.
   *
   * @param {string}                    [conversationId]  Defaults to current session ID.
   * @param {"json"|"text"|"markdown"}  [format="json"]
   * @returns {Promise<string>}
   *
   * @example
   *   // In-memory (no MongoDB needed)
   *   const txt = await ai.exportConversation(null, "text");
   *
   *   // From MongoDB
   *   await ai.enableStorage();
   *   const md = await ai.exportConversation(ai.getConversationId(), "markdown");
   */
  async exportConversation(conversationId, format = "json") {
    const cid = conversationId || this.client.conversationId;
    if (this.storage.enabled && cid) {
      return this.storage.exportConversation(cid, format);
    }
    // Fall back to in-memory export via the client
    return this.client.exportConversation(format);
  }

  // ── Persistent history & management ──────────────────────────────────────

  async getPersistentHistory(conversationId) {
    return this.storage.getConversation(conversationId || this.client.conversationId);
  }

  async listConversations()        { return this.storage.listConversations(); }
  async deleteConversation(id)     { return this.storage.deleteConversation(id); }
  async getStats()                 { return this.storage.getStats(); }
  async setPref(k, v)              { return this.storage.setPref(k, v); }
  async getPref(k, def)            { return this.storage.getPref(k, def); }
  async close()                    { await this.storage.disconnect(); }
}

module.exports = { NiyoXAI, NiyoXClient, NiyoXStorage };
