#!/usr/bin/env node
// scripts/build.js — NiyoX AI build script  v0.0.4
"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC  = path.join(ROOT, "src");
const LIB  = path.join(ROOT, "lib");

if (!fs.existsSync(LIB)) fs.mkdirSync(LIB, { recursive: true });

const client  = fs.readFileSync(path.join(SRC, "client.js"),  "utf8");
const storage = fs.readFileSync(path.join(SRC, "storage.js"), "utf8");

const cjs = `// lib/index.cjs — NiyoX AI SDK  (CommonJS — auto-generated by scripts/build.js)
"use strict";

// ─── client.js ───────────────────────────────────────────────────────────────
${client.replace(/^module\.exports.*$/m, "").trim()}

// ─── storage.js ──────────────────────────────────────────────────────────────
${storage.replace(/^module\.exports.*$/m, "").trim()}

// ─── NiyoXAI high-level class ────────────────────────────────────────────────
/**
 * NiyoXAI — high-level SDK combining the API client + optional DB storage.
 *
 * Quick start:
 *   const { NiyoXAI } = require("niyox");
 *   const ai = new NiyoXAI();
 *   const { result } = await ai.chat("Hello!");
 *
 * With persona:
 *   const ai = new NiyoXAI({ persona: "You are a concise coding assistant." });
 *   // or later:
 *   ai.setPersona("You are a friendly chef.");
 *
 * With context trimming:
 *   const ai = new NiyoXAI({ maxHistory: 20 }); // keep last 10 turns
 *
 * With MongoDB + export:
 *   const ai = new NiyoXAI({ userId: "alice" });
 *   await ai.enableStorage();
 *   await ai.chat("Hello!");
 *   const md = await ai.exportConversation(ai.getConversationId(), "markdown");
 */
class NiyoXAI {
  constructor(options = {}) {
    this.client  = new NiyoXClient(options);
    this.storage = new NiyoXStorage(options.userId || "anonymous");
  }

  // ── Storage ───────────────────────────────────────────────────────────────

  /** Enable persistent MongoDB storage. Auto-loads saved persona if client has none set. */
  async enableStorage(userId) {
    await this.storage.connect(userId);
    // Auto-restore persisted persona if none is active
    if (!this.client.getPersona()) {
      const saved = await this.storage.getPersona();
      if (saved) this.client.setPersona(saved);
    }
    return this;
  }

  // ── Persona / system-prompt (v0.0.4) ─────────────────────────────────────

  /**
   * Set the AI persona / system prompt.
   * If storage is enabled the persona is also saved to MongoDB for future sessions.
   *
   * @param {string|null} text  Pass null or "" to clear.
   * @returns {Promise<NiyoXAI>} Chainable (awaitable).
   *
   * @example
   *   await ai.setPersona("You are a concise coding assistant.");
   */
  async setPersona(text) {
    this.client.setPersona(text);
    if (this.storage.enabled) await this.storage.savePersona(text || null);
    return this;
  }

  /** Get the currently active persona string (or null). */
  getPersona() { return this.client.getPersona(); }

  // ── Context window trimming (v0.0.4) ─────────────────────────────────────

  /**
   * Set the maximum number of in-memory history entries (1 turn = 2 entries).
   * Oldest entries are pruned automatically after each turn.
   * Set to 0 for unlimited.
   *
   * @param {number} max
   * @returns {NiyoXAI} Chainable.
   *
   * @example
   *   ai.setMaxHistory(20); // keep last 10 turns
   */
  setMaxHistory(max) {
    this.client.setMaxHistory(max);
    return this;
  }

  /** Get the current maxHistory limit. */
  getMaxHistory() { return this.client.getMaxHistory(); }

  // ── Chat ──────────────────────────────────────────────────────────────────

  /** Send a message; auto-persists if storage is enabled */
  async chat(message) {
    const response = await this.client.chat(message);
    if (this.storage.enabled) {
      await this.storage.saveTurn({
        conversationId:   response.conversationId,
        userMessage:      message,
        assistantMessage: response.result,
        responseTime:     response.responseTime,
      });
    }
    return response;
  }

  /** Alias */
  async ask(message) { return this.chat(message); }

  /** Start a fresh conversation thread */
  newConversation() { this.client.newConversation(); }

  /** Get the active conversationId (null until first message sent) */
  getConversationId() { return this.client.conversationId; }

  /** In-memory history for the current session */
  getHistory() { return this.client.getHistory(); }

  // ── Conversation export (v0.0.4) ──────────────────────────────────────────

  /**
   * Export a conversation as a formatted string.
   *
   * Without storage  → exports the current in-memory session.
   * With storage     → exports the stored MongoDB conversation for \`conversationId\`.
   *
   * @param {string}                    [conversationId]  Defaults to current session ID.
   * @param {"json"|"text"|"markdown"}  [format="json"]
   * @returns {Promise<string>}
   *
   * @example
   *   // In-memory (no MongoDB needed)
   *   const txt = await ai.exportConversation(null, "text");
   *
   *   // From MongoDB
   *   await ai.enableStorage();
   *   const md = await ai.exportConversation(ai.getConversationId(), "markdown");
   */
  async exportConversation(conversationId, format = "json") {
    const cid = conversationId || this.client.conversationId;
    if (this.storage.enabled && cid) {
      return this.storage.exportConversation(cid, format);
    }
    // Fall back to in-memory export via the client
    return this.client.exportConversation(format);
  }

  // ── Persistent history & management ──────────────────────────────────────

  async getPersistentHistory(conversationId) {
    return this.storage.getConversation(conversationId || this.client.conversationId);
  }

  async listConversations()        { return this.storage.listConversations(); }
  async deleteConversation(id)     { return this.storage.deleteConversation(id); }
  async getStats()                 { return this.storage.getStats(); }
  async setPref(k, v)              { return this.storage.setPref(k, v); }
  async getPref(k, def)            { return this.storage.getPref(k, def); }
  async close()                    { await this.storage.disconnect(); }
}

module.exports = { NiyoXAI, NiyoXClient, NiyoXStorage };
`;

const mjs = `// lib/index.mjs — NiyoX AI SDK  (ESM — auto-generated by scripts/build.js)
import cjs from "./index.cjs";
export const { NiyoXAI, NiyoXClient, NiyoXStorage } = cjs;
export default cjs.NiyoXAI;
`;

fs.writeFileSync(path.join(LIB, "index.cjs"), cjs, "utf8");
fs.writeFileSync(path.join(LIB, "index.mjs"), mjs, "utf8");

console.log("✓  Built lib/index.cjs");
console.log("✓  Built lib/index.mjs");
